### ISSUE TITLE
Stepper motor pi reference - diagram

### ISSUE THREAD

**Issue by MK2TTRS613** [bigtreetech/Rodent#2]
Pin references in the pin-out diagram, X/Z have the same pin reference  and so those Y/E
<img width="207" alt="Screenshot 2024-11-30 at 10 39 48 AM" src="https://github.com/user-attachments/assets/4ff81683-1ecf-49cf-8557-9bb393a85af0">

**Comment by bigtreetech** [comment]
Corrected.
