### ISSUE TITLE
User manual correction

### ISSUE THREAD

**Issue by MK2TTRS613** [bigtreetech/Rodent#4]
There is no mention in the manual of adding a jumper to power up the motherboard via a USB cable in order to upload the firmware.

**Comment by MK2TTRS613** [comment]
These link would be a better reference to install firmware onto the Rodent[ ](http://wiki.fluidnc.com/en/installation) instead of the link to the GitHub page.

**Comment by BTTJUSTIN** [comment]
The documentation has been updated(v1.01 ). Thanks again for pointing out the issue
